### ISSUE TITLE
Androidtv RuntimeError: ERROR: 'FAIL' 0006closed

### ISSUE THREAD

**Issue by RutgerJoosten** [hassio-addons/addon-adb#10]
# Problem/Motivation

Edit: I think I created this issue in the wrong place it should be under the component not the ADB addon, sorry about this, but I don't see where I can change this..

I have a problem with the androidtv component not wanting to load when Hass is (re)started
When it works it is awesome! But the androidtv component won't start most of the time.

The error from the log:

```
Log Details (ERROR)
Sun Mar 24 2019 22:59:14 GMT+0100 (Midden-Europese standaardtijd)
Error while setting up platform androidtv
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/androidtv/media_player.py", line 115, in setup_platform
    device_class=config[CONF_DEVICE_CLASS])
  File "/config/deps/lib/python3.7/site-packages/androidtv/__init__.py", line 34, in setup
    return AndroidTV(host, adbkey, adb_server_ip, adb_server_port)
  File "/config/deps/lib/python3.7/site-packages/androidtv/androidtv.py", line 59, in __init__
    self.device_properties = self.get_device_properties()
  File "/config/deps/lib/python3.7/site-packages/androidtv/androidtv.py", line 146, in get_device_properties
    properties = self.adb_shell('getprop')
  File "/config/deps/lib/python3.7/site-packages/androidtv/basetv.py", line 122, in _adb_shell_pure_python_adb
    return self._adb_device.shell(cmd)
  File "/config/deps/lib/python3.7/site-packages/adb_messenger/command/transport/__init__.py", line 23, in shell
    conn.send(cmd)
  File "/config/deps/lib/python3.7/site-packages/adb_messenger/connection.py", line 77, in send
    return self._check_status()
  File "/config/deps/lib/python3.7/site-packages/adb_messenger/connection.py", line 83, in _check_status
    raise RuntimeError("ERROR: {} {}".format(repr(recv), error))
RuntimeError: ERROR: 'FAIL' 0006closed
```
I am running  hassio 0.90.1 with the ADB addon (0.3.0)
The ADB is able to connect because the log is showing this a lot:
```
[22:51:29] INFO: Connecting to device: 192.168.178.117...
already connected to 192.168.178.117:5555
[22:51:29] INFO: Connecting to device: 192.168.178.118...
already connected to 192.168.178.118:5555
```

## Expected behavior

I would like to control my sony bravia android tv

## Actual behavior

Sometimes the component works, but then after I restart Hass it sometimes wont start the component and gives me an error in the log. I can continue to restart Hass until I get lucky after a few tries and the component will work. This is a bit annoying :p

## Steps to reproduce

I have no idea actually..

## Proposed changes

I have no idea.. 

I am also running a custom component Sony Bravia PSK (https://community.home-assistant.io/t/sony-bravia-tv-component-with-pre-shared-key/30698)
This let me control my tv with a pre shared key. Could this stand in the way of the androidtv component? When I comment out the sony custom component in my configuration.yaml there is no change in the androidtv issue

Hopefully someone can help me with this. :)

<blockquote><img src="https://community-home-assistant-assets.s3-us-west-2.amazonaws.com/original/3X/e/b/eb650661cff504ec89b0a3c5546321eee944b624.jpg" width="48" align="right"><div><img src="https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/f/4/f42b82971fce994297fbc2b269efa248beef897b.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/sony-bravia-tv-component-with-pre-shared-key/30698">Sony Bravia TV component with Pre-Shared Key</a></strong></div><div>Using Home Assistant for some weeks now and it works great 😎  I have a Sony Bravia TV and I have used the braviatv platform, but that was not working very well for me.  After some days the state card wasn’t updating anymore and I got a lot of errors in the log. Only a restart of HASS would fix that problem.  I think this was caused by the PIN/cookie method which isn’t working fine (at least not in my setup).  That’s why I have made a custom component which is using a Pre-Shared Key to...</div></blockquote>

**Comment by frenck** [comment]
This indeed is a component thing.

Please report the issue with the component here:
https://github.com/home-assistant/home-assistant
