### ISSUE TITLE
Device unauthorized even after accepting the confirmation

### ISSUE THREAD

**Issue by arsaboo** [hassio-addons/addon-adb#3]
# Problem/Motivation

I added the addon and it works fine with my Shield. For my FireTV, even after accepting the permission prompt, I see the following error:

```bash
Tue Feb 05 2019 07:56:44 GMT-0500 (Eastern Standard Time)
Error while setting up platform androidtv
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/androidtv.py", line 191, in setup_platform
    adb_server_port=config[CONF_ADB_SERVER_PORT])
  File "/config/deps/lib/python3.6/site-packages/androidtv/__init__.py", line 230, in __init__
    self.properties = self.device_info()
  File "/config/deps/lib/python3.6/site-packages/androidtv/__init__.py", line 325, in device_info
    properties = self._adb_shell('getprop')
  File "/config/deps/lib/python3.6/site-packages/androidtv/__init__.py", line 479, in _adb_shell_pure_python_adb
    return self._adb_device.shell(cmd)
  File "/config/deps/lib/python3.6/site-packages/adb_messenger/command/transport/__init__.py", line 20, in shell
    conn = self.create_connection(timeout=timeout)
  File "/config/deps/lib/python3.6/site-packages/adb_messenger/device.py", line 45, in create_connection
    self.transport(conn)
  File "/config/deps/lib/python3.6/site-packages/adb_messenger/command/transport/__init__.py", line 15, in transport
    connection.send(cmd)
  File "/config/deps/lib/python3.6/site-packages/adb_messenger/connection.py", line 77, in send
    return self._check_status()
  File "/config/deps/lib/python3.6/site-packages/adb_messenger/connection.py", line 83, in _check_status
    raise RuntimeError("ERROR: {} {}".format(repr(recv), error))
RuntimeError: ERROR: 'FAIL' 00a7device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
```

Interestingly, in the addon log, I see successful connections for both my devices:
```
INFO: Connecting to device: 192.168.2.28...
already connected to 192.168.2.28:5555
INFO: Connecting to device: 192.168.2.225...
already connected to 192.168.2.225:5555
```
Is there a way to manually kill server in the addon and try again?

**Comment by arsaboo** [comment]
I am not sure what was the issue. I deleted and reinstalled everything and now it is working.

**Comment by frenck** [comment]
Thanks for letting me know! Nevertheless, I have absolutely no clue on how this can/could happen at this point
