### ISSUE TITLE
Not working on HA 0.88

### ISSUE THREAD

**Issue by Supersimo88** [hassio-addons/addon-adb#8]
After upgrading home assistant to version 0.88, the andoridtv component no longer works. Even changing the folder structure in /config/custom_components/androidtv/media_player.py does not solve the problem.

**Comment by sinclairpaul** [comment]
Have you got the latest androidtv.py?

**Comment by gerard33** [comment]
I can confirm it works on HA 0.88 using the latest version of `androidtv.py` found [here](https://raw.githubusercontent.com/hassio-addons/addon-adb/master/custom_components/media_player/androidtv.py).

**Comment by morrisb74** [comment]
Same problem as Supersimo (I guess)

But here is some info from the log:
```ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform androidtv
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/media_player/androidtv.py", line 196, in setup_platform
    adb_server_port=config[CONF_ADB_SERVER_PORT])
  File "/config/deps/lib/python3.7/site-packages/androidtv/__init__.py", line 249, in __init__
    self.properties = self.device_info()
  File "/config/deps/lib/python3.7/site-packages/androidtv/__init__.py", line 447, in device_info
    wifimac = re.findall(WIFIMAC_REGEX_PATTERN, wifi_out)[0]
IndexError: list index out of range
```

**Comment by Supersimo88** [comment]
I tried to update to the latest version but it does not work


 Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/androidtv/media_player.py", line 200, in setup_platform
    if not atv.available:
  File "/config/deps/lib/python3.7/site-packages/androidtv/__init__.py", line 521, in available
    adb_devices = self._adb_client.devices()
  File "/config/deps/lib/python3.7/site-packages/adb_messenger/command/host/__init__.py", line 19, in devices
    result = self._execute_cmd(cmd)
  File "/config/deps/lib/python3.7/site-packages/adb_messenger/command/host/__init__.py", line 10, in _execute_cmd
    conn.send(cmd)
  File "/config/deps/lib/python3.7/site-packages/adb_messenger/connection.py", line 77, in send
    return self._check_status()
  File "/config/deps/lib/python3.7/site-packages/adb_messenger/connection.py", line 80, in _check_status
    recv = self._recv(4).decode('utf-8')
  File "/config/deps/lib/python3.7/site-packages/adb_messenger/connection.py", line 56, in _recv
    return self.socket.recv(length)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by frenck** [comment]
The component in this repository has been updated.
Please note, the location of where the custom component should be placed, has changed.
See the main add-on README/manual for instructions.

@Supersimo88 `ConnectionResetError: [Errno 104] Connection reset by peer` is an unrelated error to this issue. Drop by on our Discord, since that seems to be a network related issue.
